### ISSUE TITLE
global: load ACCOUNTS_SESSION_REDIS_URL from enviroment

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-accounts#109]
Issue: On mac when redis is run in a docker machine the host ip is the one of the virtual box vm, not localhost. The default value of ACCOUNTS_SESSION_REDIS_URL is hard coded (https://github.com/inveniosoftware/invenio-accounts/blob/434f56e5c10bf2f7f996d03880c43ff2e094a08b/invenio_accounts/config.py#L29). Thus docker cannot be used when running tests on a mac.

Solution: load ACCOUNTS_SESSION_REDIS_URL from environment if it is set. This solution is already used in invenio-search (https://github.com/inveniosoftware/invenio-search/blob/f19a3c743ad9d578d0840a416e7dd76e6fffca06/invenio_search/config.py#L58)

**Comment by jirikuncar** [comment]
It is already implemented in Invenio-Base / Invenio-Config.

--
Thanks for the tip in Invenio-Search. I have created issue https://github.com/inveniosoftware/invenio-search/issues/51.
