### ISSUE TITLE
models: Add a 'nickname' field to User?

### ISSUE THREAD

**Issue by emanueldima** [inveniosoftware/invenio-accounts#151]
In B2SHARE, our login service provides a 'nickname' for each user. For UI is nicer to show the nickname of the user and not the email address.

**Comment by hachreak** [comment]
maybe you can use [invenio-userprofiles](https://github.com/inveniosoftware/invenio-userprofiles/blob/master/invenio_userprofiles/models.py#L77)?

**Comment by lnielsen** [comment]
Yes, this is already implanted via the invenio-userprofiles module. However, you can also use invenio-oauthclient to link [external identities](https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/models.py#L224) with a local account. Not sure what would be most appropriate in your use case.

**Comment by jirikuncar** [comment]
@emanueldima using external identities (or RemoteAccount.extra_data) is probably way to go since you don't want users to modify it on your site.
