### ISSUE TITLE
admin: user creation doesn't work

### ISSUE THREAD

**Issue by PXke** [inveniosoftware/invenio-accounts#154]
If you use different way to create user. 

With the /signup/ url, or the admin interface, or the cli. It seems they all ignore each others. 

For example if I create 4 users with admin it will allocate 1-4 for ids then if I use the CLI I will have to crash it four times to make it create a user with the id 5. 

Way to create, ID 
Admin UI, 1
Admin UI, 2
Admin UI, 3
CLI, 1 -> crash 
CLI, 2 -> crash
CLI, 3 -> crash
CLI, 4

**Comment by lnielsen** [comment]
This seems to be a problem with the admin interface - honestly I think user creation via admin haven't been tested at all. For once, the admin shouldn't ask to fill in the id, also it shouldn't allow editing/changing some of the timestamps.

<img width="745" alt="screen shot 2016-09-08 at 14 42 59" src="https://cloud.githubusercontent.com/assets/1698163/18349628/8f297cae-75d2-11e6-972f-2eec9a7e26ca.png">

**Comment by lnielsen** [comment]
Probably the creation form should only have:

- Email
- Active

We could enable "confirmed at", which controls if an account's email address was confirmed or not so that an admin can confirm an email address for a given user, but not sure it's a good idea.
