### ISSUE TITLE
tests: missing invenio-access

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-accounts#18]
### Problem

Invenio-Access is installed in Invenio, but it's not required in `PACKAGES`. However the models get loaded and are causing troubles during account deletion in tests.

- [ ] https://github.com/inveniosoftware/invenio-accounts/blob/master/.travis.invenio.cfg#L34

**Comment by hachreak** [comment]
Did you mean these errors?

```
"Table 'invenio.user_accROLE' doesn't exist"
```

**Comment by jirikuncar** [comment]
@hachreak exactly. It's probably because invenio-access is loaded through `invenio.ext.login.legacy_user`.

**Comment by jirikuncar** [comment]
Fixed via #22.
