### ISSUE TITLE
global: logout_listener fails when using logout_user

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-accounts#197]
**Problem:**
Using `logout_user()` after calling `login_user(user)` in tests will fail. This happens because they are used in a `test_request_context` and, as [explained in flask documentation](http://flask.pocoo.org/docs/0.12/testing/#other-testing-tricks)

*"the `before_request()` and `after_request()` functions are not called automatically."*

As [`login_listener`](https://github.com/inveniosoftware/invenio-accounts/blob/559284550f4b6f2fa964f11be27fc269489dbf43/invenio_accounts/sessions.py#L58)creates the session after the request, using `@flask.after_this_request`, the session is not created when calling `login_user(user)`. However  [`logout_listener`](https://github.com/inveniosoftware/invenio-accounts/blob/559284550f4b6f2fa964f11be27fc269489dbf43/invenio_accounts/sessions.py#L79) deletes the session immediately instead of also doing it in `@flask.after_this_request`, which fails as the session does not exist.

**Suggested solution:**
Moving the code [deleting the session](https://github.com/inveniosoftware/invenio-accounts/blob/559284550f4b6f2fa964f11be27fc269489dbf43/invenio_accounts/sessions.py#L85-L87) in the [after request function](https://github.com/inveniosoftware/invenio-accounts/blob/559284550f4b6f2fa964f11be27fc269489dbf43/invenio_accounts/sessions.py#L89).

@lnielsen Do you see any issue with the suggested solution. All the tests in invenio-accounts and invenio-oauthclient seem to pass when I do this.

**Comment by lnielsen** [comment]
No. But just test the login/logout in the browser with two separate sessions: 1) Login session a 2) Login session b 3) View security tab in both sessions and see that there's two sessions. 4) Logout from session a 5) Check in session b the security tab and verify that only one session is now displayed.

**Comment by nharraud** [comment]
@lnielsen I just tested with invenio-app-ils. It works.
Also [the test you created](https://github.com/inveniosoftware/invenio-accounts/blob/master/tests/test_sessions.py#L98) to check that sessions are removed still passes as it calls logout via the views, which means that the after request triggers are called properly.
