### ISSUE TITLE
accounts: create manage hooks

### ISSUE THREAD

**Issue by eamonnmag** [inveniosoftware/invenio-accounts#2]
So that we can create users for example for inveniomanage, e.g.

```
inveniomanage user createsuperuser --u eamonn --p mypassword --e eamonn@helloworld.com
inveniomanage user createuser --u eamonn --p mypassword --e eamonn@helloworld.com
```

**Comment by jirikuncar** [comment]
#### Proposal

@eamonnmag I like your proposal, I have just few consistency suggestions:

`inveniomanage accounts create [--superadmin] -u/--user <name> -e/--email <valid_email> [-p/--passoword]`

**Question**

Shall we create commands for deleting and modifying users too?

**Comment by eamonnmag** [comment]
I like your option better. I was just going with how django does it. They only have 

```
 changepassword
 createsuperuser
``` 

I think that having the ability to create and modify any type of user from this tool would be very useful though.

**Comment by jirikuncar** [comment]
:+1: for `changepassword`

**Comment by tiborsimko** [comment]
:+1: and it'll be good to grow options later to be able to delete users, make them inactive, etc.  (E.g. merge users would be fun to have later.)

**Comment by lnielsen** [comment]
:+1: for adding simple options. Especially useful for development and bootstrapping. In a running  production I would prefer to have most stuff in the UI (which naturally doesn't exclude also having it in CLI as well).

**Comment by eamonnmag** [comment]
```addrole' would also be good. We need to add roles to users, and there's nothing I see on the front end side to do that yet. I may make a start on this soon, since we really need it.

**Comment by jirikuncar** [comment]
@eamonnmag `addrole` should be probably part of `invenio-access` package. (cc @hachreak)

**Comment by eamonnmag** [comment]
Ah, ok, I didn't know about that. Where is that package currently residing? I can't find it anywhere.

**Comment by jirikuncar** [comment]
@eamonnmag created here https://github.com/inveniosoftware/invenio-access and it's waiting for https://github.com/inveniosoftware/invenio/pull/3328 to be integrated first.

**Comment by eamonnmag** [comment]
Great, thanks @jirikuncar!

**Comment by lnielsen** [comment]
Btw, just for reference here's the commands from Flask-Security: https://github.com/mattupstate/flask-security/blob/develop/flask_security/script.py:

- Create user
- Create role
- Add/remove role to/from user
- Activate/deactivate  user

**Comment by eamonnmag** [comment]
Can we not just use this?

**Comment by lnielsen** [comment]
You mean use Flask-Security, or just use the names?

Names: Yes, I'm fine with them.
Flask-Security: Yes as well, but on a longer time scale. I've already done some integration work for Flask-AppFactory with Flask-Security.

**Comment by jirikuncar** [comment]
Superseded by #32.
