### ISSUE TITLE
docs: example application not rendered on readthedocs

### ISSUE THREAD

**Issue by hjhsalo** [inveniosoftware/invenio-accounts#214]
Fixable for example as done in invenio-admin:
https://raw.githubusercontent.com/inveniosoftware/invenio-admin/master/docs/examplesapp.rst
https://github.com/inveniosoftware/invenio-admin/blob/master/examples/app.py#L27
https://github.com/inveniosoftware/invenio-admin/blob/master/examples/app.py#L58

**Comment by lnielsen** [comment]
Fixed in #215
