### ISSUE TITLE
alembic: wrongly naming the foreign key constraint fk_transaction_accounts_user_id

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-accounts#219]
**Problem:**
The alembic recipe `9848d0149abd_create_accounts_tables.py` [creates a foreign key named `fk_transaction_accounts_user_id`](https://github.com/inveniosoftware/invenio-accounts/blob/a444115e0099cb311112273889edb3c9908ddb3c/invenio_accounts/alembic/9848d0149abd_create_accounts_tables.py#L98)  between the SQLAlchemy-Continuum's `transaction` table and the invenio-accounts'  `accounts_user` table.

The problem is that
- SQLAlchemy-Continuum [does not name the corresponding foreign key constraint in its model](https://github.com/kvesteri/sqlalchemy-continuum/blob/5f682e6e5bf038d8069db51e58f71d2c1dbed6c6/sqlalchemy_continuum/transaction.py#L150).
- invenio-db has a recipe `35c1075e6360_force_naming_convention.py` enforcing a naming convention and [renaming forcefully any constraint](https://github.com/inveniosoftware/invenio-db/blob/4df7ce16c2ae3f86f92596b1be4223f38604e543/invenio_db/alembic/35c1075e6360_force_naming_convention.py#L77-L88).
- the recipe `9848d0149abd_create_accounts_tables.py` [does not depend on recipe `35c1075e6360_force_naming_convention.py` but on a previous recipe](https://github.com/inveniosoftware/invenio-accounts/blob/a444115e0099cb311112273889edb3c9908ddb3c/invenio_accounts/alembic/843bc79c426f_create_accounts_branch.py#L34).

Thus `9848d0149abd_create_accounts_tables.py` and `35c1075e6360_force_naming_convention.py` run in random order and force either the foreign key constraint name `fk_transaction_accounts_user_id` or `fk_transaction_user_id_accounts_user` (as generated by the naming convention). **Thus It is not possible to know which name the constraint will have after running `alembic upgrade`.**

**Solution.**
We should not name the constraint in `9848d0149abd_create_accounts_tables.py`. That way the resulting name will always be the one from the naming convention, i.e. `fk_transaction_user_id_accounts_user`, once the recipe `35c1075e6360_force_naming_convention.py` has ran. However it also means that as long as `35c1075e6360_force_naming_convention.py` is not called the name can vary. This should not be a problem as the module is still in beta and alembic upgrades are not yet officially supported.

cc: @lnielsen, @egabancho, @tiborsimko, @remileduc, @PXke, @kaplun

**Comment by kaplun** [comment]
cc @jmartinm

**Comment by nharraud** [comment]
Note: for B2SHARE we are currently working on having our own upgrade scripts doing all the hacks needed like renaming + using alembic. We are planning a presentation on how we proceed.

**Comment by nharraud** [comment]
cc @dinosk
