### ISSUE TITLE
RFC Remove or keep "Remember me" feature?

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-accounts#226]
To remember me or not to remember me that's the question.

Currently the "Remember me" together with the session activity tracking is broken:

E.g. you have two sessions with remember me open, then from session 1 you revoke the session 2. What will happen when the browser window with session 2 is reload is that the user is logged in via the remember me token (also when a user is logged in via remember me, the session activity tracking is not created). This should not happen since you revoked the session (when you logout, the remember me token is removed)

Now the question is if we really need the remember me feature anymore? Currently we are using permanent sessions with lifetime of 31 days. I think the remember me feature is useful if you have short session lifetime (like minutes or hours), but probably not when you have long session life times.

**Proposal 1: Remove remember me**
This will solve all problems with remember me loopholes. 

**Proposal 2: Keep remember me**
We will need to monkey patch Flask-Security and Flask-Login to make it work with the session activity tracking.

Any strong opinions on either side?
@jacquerie @jmartinm This affects you related to your recent PR in oauthclient: inveniosoftware/invenio-oauthclient#134

**Comment by jmartinm** [comment]
> Any strong opinions on either side?
@jacquerie @jmartinm This affects you related to your recent PR in oauthclient: inveniosoftware/invenio-oauthclient#134

@lnielsen do you have a config variable set for 31 days? Because by default for us the session cookie was expiring with the browser session and that's why we needed the remember me functionality (which then allows for 1 year expiration).

If we can set it for 31 days and that avoids other problems, it should be ok for us.

**Comment by lnielsen** [comment]
It is controlled through Flask's [``PERMANENT_SESSION_LIFETIME``](http://flask.pocoo.org/docs/0.12/config/#builtin-configuration-values). If it it's ``False`` sessions expire with the browser session (i.e. non-persistent cookie), if you set it to a ``timedelta`` the the session is permanent (i.e.  persistent browser cookie). 

Flask is setting this [by default to 31 days](https://github.com/pallets/flask/blob/master/flask/app.py#L295), so most likely you are changing it explicitly in expire?

**Comment by lnielsen** [comment]
I don't see that ``PERMANENT_SESSION_LIFETIME`` is set in your source code, so perhaps it's set in the puppet configuration or similar?

**Comment by lnielsen** [comment]
@jmartinm did you have a chance to check if ``PERMANENT_SESSION_LIFETIME`` is set to ``False`` somewhere in your code?

**Comment by jmartinm** [comment]
Locally, if I access a given view and check if the session is permanent:

```python
from flask import session
session.permanent
False
```

For permanent session something like https://stackoverflow.com/a/37754039/890185 needs to be done.

I created a PR in invenio-accounts https://github.com/inveniosoftware/invenio-accounts/pull/230it looks ok, I can add some test there
