### ISSUE TITLE
docs: document that you have to run celery beat task to clean session table

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-accounts#227]

**Comment by hachreak** [comment]
Is it already [documented](https://github.com/inveniosoftware/invenio-accounts/blob/master/docs/configuration.rst)?

**Comment by lnielsen** [comment]
Yes, but it's very hidden. @krzysztof and @slint where upgrading packages on Zenodo and I saw that this particular thing is important but very hidden. I would expect to find it in https://invenio-accounts.readthedocs.io/en/latest/configuration.html

**Comment by lnielsen** [comment]
I'm blind :-) It's already done
