### ISSUE TITLE
global: fork or integrate Flask-KVSession

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-accounts#289]
Flask-KVSession is [currently abandoned](https://github.com/mbr/flask-kvsession/commits/master) (but [`simplekv` is not](https://github.com/mbr/simplekv/commits/master)). There are a couple of issues/features that are necessary for supporting `SameSite` cookies, and client-side sessions.

To address these, the package has to either be forked in `inveniosoftware`, or integrated inside `invenio-accounts` (e.g. in `session.py`). Forking seems to be the better option at the moment since we would also keep the existing unit tests of the package.

**Comment by ppanero** [comment]
Released as https://pypi.org/project/Flask-KVSession-Invenio/

**Comment by ntarocco** [comment]
@diegodelemos @ppanero @Glignos shouldn't we change the URL in the [setup.py](https://github.com/inveniosoftware/flask-kvsession/blob/master/setup.py#L19)?
I am not sure what is the best thing to do in case of forking and releasing forked packages, but I went on PyPi and the URL is to the original repo... a bit misleading.

**Comment by ppanero** [comment]
@ntarocco yes, my bad. Added to https://github.com/inveniosoftware/flask-kvsession/issues/6
