### ISSUE TITLE
cli: change to flat structure

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-accounts#29]
Change CLI to flat structure:

from:

```
inveniomanage accounts users create
inveniomanage accounts users activate
inveniomanage accounts users deactivate
inveniomanage accounts roles add
inveniomanage accounts roles create
inveniomanage accounts roles remove
```

to 

```
inveniomanage accounts createuser
inveniomanage accounts activateuser
inveniomanage accounts deactivateuser
inveniomanage accounts addrole
inveniomanage accounts createrole
inveniomanage accounts removerole
```

**Comment by lnielsen** [comment]
Ping @tiborsimko - can you check the naming?

**Comment by tiborsimko** [comment]
I think a leading namespace prefix convention would be nice, like GNU/Linux is using in commands `useradd`,  `userdel`,  `usermod` (though there is also `adduser`...)

With CLI auto-completion, we could have

- `inveniomanage accounts usercreate`
- `inveniomanage accounts userdelete`
- `inveniomanage accounts rolecreate`
- `inveniomanage accounts roledelete`

etc.  Typing `user TAB`, triggering auto-completion, and seeing all actions that are available to manipulate users, seems useful.

P.S. BTW another naming decision may be words coming in pairs, such as add/remove, create/destroy, with a chain like "create -> add -> remove -> destroy".

**Comment by JavierDelgadoFernandez** [comment]
@lnielsen I have updated the commands according to the suggestion. @tiborsimko I also agree with the use of pair words, actually Unix uses "useradd" to create user instead of "usercreate". This change is easy.

**Comment by jirikuncar** [comment]
IMHO the original with hierarchy is easier to read, moreover after reading following comment ...

> Typing `user TAB`, triggering auto-completion, and seeing all actions that are available to manipulate users, seems useful.

If there was a need for change why following schema was not considered?

```
inveniomanage accounts add <type(user|role)>
inveniomanage accounts delete <type(user|role)>
```
