### ISSUE TITLE
Version 1.1.3 causes conflict with invenio 3.1.2 and invenio-celery

### ISSUE THREAD

**Issue by jma** [inveniosoftware/invenio-accounts#306]
Updating dependencies was not a good idea for the version 1.1.3:
https://github.com/inveniosoftware/invenio-
accounts/commits/04678c1f3b36591dd1fdc0a842decc328c736db0

as it provides invenio-celery dependency impossible to solve as:
invenio-accounts 1.1.3 ask 'invenio-celery>=1.1.2'
and
invenio 3.1.2 ask 'invenio-celery>=1.0.1,<1.1.0'

**Comment by ppanero** [comment]
Hi @jma,

Invenio v3.1.x supports

- Invenio-Accounts v1.1.x
- Invenio-Celery v1.0.x

Invenio-Accounts v1.1.X (Latest is v1.1.4 is supported by Invenio v3.2)
