### ISSUE TITLE
cli: change structure

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-accounts#32]
Reiteration on #29

CLI conventions:
- Max 2 levels
- Command naming:
  - <cmd> <noun> <verb>
  - no compound names (e.g. ``usercreate``)

Open questions:
- Plural vs singular?

```console
$ inveniomanages user create
$ inveniomanages role add
```
vs.
```console
$ inveniomanages users create
$ inveniomanages roles add
```

**Comment by jirikuncar** [comment]
I would go for plural version and possibility to create "batch" addition/creation/deletion.
