### ISSUE TITLE
admin: admin interface for accounts

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-accounts#33]
Once Invenio-Admin is integrated, add admin interface for managing users.

1) Support for batch actions: active/deactivate user.
2) User deactivation must ensure that user get's logged out immediately (i.e. kill session).
3) By default sort by last_login
4) Add filters to quickly filter list of users.

Open Question:
- Will we support the old "Become user" feature? (ping @tiborsimko @jirikuncar) IMHO it's not good that an admin can impersonate a user.

**Comment by jirikuncar** [comment]
> 2) User deactivation must ensure that user get's logged out immediately (i.e. kill session).

This might be tricky if we don't know the session id. We can't realy call `logout_user` on before update/delete. Instead we might need to override `find_user` (https://github.com/mattupstate/flask-security/blob/develop/flask_security/datastore.py#L202-L203) to check if user is active or not (see place where it's used https://github.com/mattupstate/flask-security/blob/develop/flask_security/core.py#L191).

**Comment by lnielsen** [comment]
https://flask-admin.readthedocs.org/en/latest/advanced/#customizing-batch-actions

**Comment by jirikuncar** [comment]
Closed via f2e449ca and d269e473.

> Will we support the old "Become user" feature?

Admin should be able to do everything with superuser rights. User access right verification can be done via Python console if needed.
