### ISSUE TITLE
i18n: message catalogs not being compiled due to "fuzzy"

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-accounts#346]
Package version (if known): 1.3.0

## Describe the bug

The distributed package on PyPI doesn't compile the message catalog of most languages (i.e we're lacking the .mo file). This is due to ``fuzzy`` being included in the [messages.po](https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/translations/it/LC_MESSAGES/messages.po#L7).

Example of a good [messages.po](https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/translations/da/LC_MESSAGES/messages.po) which does not include "fuzzy" and where the .mo file is correctly compiled.

### Screenshot

Screenshot from files included in the PyPI distribution:
![Screenshot 2020-10-15 at 11 46 31](https://user-images.githubusercontent.com/1698163/96106933-12723280-0edc-11eb-87f3-6e982a1dac5d.png)

**Comment by libremente** [comment]
Are those strings correctly reviewed? 
`#, fuzzy is the mark that gettext uses to determine that a translation content has to be reviewed. While this mark is there, the translation won't show up in run-time.`
For example, in the Italian case I can see that 0% of the translations are reviewed and this explains the #fuzzy parameter being set
![Schermata da 2020-10-20 18-43-56](https://user-images.githubusercontent.com/25111463/96617772-4f875c00-1304-11eb-9b97-fcb085783810.png)


Ref: https://docs.transifex.com/formats/gettext#fuzzy-matches

**Comment by lnielsen** [comment]
Note for the coming sprint:

- All Invenio v3.4 modules should be checked. See list of modules in ``setup.py`` - https://github.com/inveniosoftware/invenio/blob/master/setup.py
