### ISSUE TITLE
ui: reset password should not display login/signup with user is autenticated

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-accounts#35]
1. Login with a user
2. Go to http://localhost:5000/reset

The bottom part of the form should only be available when the user is not authenticated.

![screen shot 2015-11-02 at 12 46 31](https://cloud.githubusercontent.com/assets/1698163/10881040/f38db43e-815f-11e5-8d46-6c04fd31de33.png)

**Comment by SamiHiltunen** [comment]
@lnielsen Fixed in #37. Future Flask-Security release will not allow password resetting for authenticated users though.
