### ISSUE TITLE
installation: extension should not provide config  entrypoint

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-accounts#370]
Package version (if known): <version>

## Describe the bug

A config entry point was added to Invenio-Accounts:

```
[2021-05-20 22:18:32,819] DEBUG in entrypoint: Loading config for entry point invenio_accounts = invenio_accounts.config
```

https://github.com/inveniosoftware/invenio-accounts/blob/master/setup.py#L127-L129

## Additional context

An Invenio module should load config through the extension and not through a config entrypoint. Otherwise it's not possible to properly override the configuration in an Invenio instance.

**Comment by ntarocco** [comment]
Discussed changes with @max-moser:
1. remove the config entrypoints from both modules
2. document better the config vars, explaining that have to be set in the final app
3. change the rdm cookiecutter instance to add such config vars

**Comment by ntarocco** [comment]
Fixed here:
* https://github.com/inveniosoftware/invenio-accounts/pull/371
* https://github.com/inveniosoftware/invenio-oauthclient/pull/253
