### ISSUE TITLE
Flask-Login>0.3 is_authenticated and is_anonymous becoming properties

### ISSUE THREAD

**Issue by SamiHiltunen** [inveniosoftware/invenio-accounts#41]
Flask-Login changed is_authenticated() and is_anonymous() to properties in >0.3 versions. This will causes issues as the development version of Flask-Security pin Flask-Login to >0.3 version. For now, I've commented out Flask-Security from the development requirements. When the new version is released, we should pin the version to the new one and amend calls to is_authenticated and is_anonymous.

Related: 
 - PR #37 
 - mattupstate/flask-security#433

**Comment by jirikuncar** [comment]
Closed via 2ffc5866c6788488c8a5758fb6b2a45a62eeca50
