### ISSUE TITLE
tests: add tests for user deactivation

### ISSUE THREAD

**Issue by otron** [inveniosoftware/invenio-accounts#44]
Need test(s) that verify that a user, once deactivated, immediately has their session(s) invalidated and are unable to log in.

Test description:
1. Create user X
2. log in as X
3. deactivate user X
4. try to do _things_ as user X. Result should be the same as trying to do so as any anonymous/unauthenticated user

**Comment by otron** [comment]
How do we deactivate a user in `invenio-accounts`? Do we use `flask_security.datastore.deactive_user(user)`[0]?

[0]: https://pythonhosted.org/Flask-Security/api.html?highlight=deactivate#flask_security.datastore.UserDatastore.deactivate_user

**Comment by lnielsen** [comment]
The admin should provide a filter action to deactivate multiple users at once, which should use the Flask-Security datastore.deactivate_user under the hood.

**Comment by otron** [comment]
Admin as in `invenio-admin`?

**Comment by lnielsen** [comment]
In #33

**Comment by jirikuncar** [comment]
Solved as part of #33.
