### ISSUE TITLE
global: session activity feature

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-accounts#52]
We need the ability to destroy a valid session without the user making a request (this is useful to e.g. ban users immediately #44). Also, this can be used to allow users to see a list of their active sessions (e.g. from multiple devices, and logout a specific device). This is only really possible when sessions are stored server-side (i.e #51). We also need to associate a session (for a logged in user) with a user id (Flask-Session/KVSession use uuids as session ids).

- [x] Model: user, session, timestamp (UTC), country, browser, os (deduced from ip and user agent)
- [x] Connect to Flask-Login's `user_logged_in` signal to store the session activity when a user logins.
- [x] Celery cron task to clean up session activity table.
- [x] Account settings item "Security", with a panel that list Sessions (see e.g. DropBox as an example). Allow a user to remove a session plus "Log me out of all devices". I would also include "Change password" on the same page.
- [x] Model: +country, browser, browser version, os (deduced from ip and user agent)
- [x] Configuration: Allow 1) tracking only user/session/timestamp and not country, browser and os 2) completely switching off the session activity feature.
- [x] Admin interface (needs very restrictive permissions). Browse, remove, filter by user. (related to #33)

**Comment by jirikuncar** [comment]
@lnielsen I'm not sure if all tasks were done in https://github.com/inveniosoftware/invenio-accounts/pull/65. Shall we re-open and mark tasks that has been done?

**Comment by lnielsen** [comment]
@hachreak We should as minimum add the celery clean up script and "security" so user have full control of their session data.

**Comment by lnielsen** [comment]
Closed by 1ade848
