### ISSUE TITLE
celery: ACCOUNTS_USE_CELERY should be configurable and not overridden.

### ISSUE THREAD

**Issue by eamonnmag** [inveniosoftware/invenio-accounts#82]
At present, there is no ability to override this config option since this line in ext always sets the variable depending on the mode the app is running in.

https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/ext.py#L76

**Comment by jirikuncar** [comment]
@eamonnmag `app.config.setdefault` is used so one can override this config option.

Please make sure that you have something like this in your `factory.py`.
```python
from invenio_config import create_conf_loader
from . import config

env_prefix = 'APP'
conf_loader = create_conf_loader(config=config, env_prefix=env_prefix)

create_api = create_app_factory(
    ...
    config_loader=conf_loader,
    ...
)
```

**Comment by eamonnmag** [comment]
I have that, but it's still sending the account emails via celery.

```python
env_prefix = 'APP'

conf_loader = create_conf_loader(config=config, env_prefix=env_prefix)

instance_path = os.getenv(env_prefix + '_INSTANCE_PATH') or \
    os.path.join(sys.prefix, 'var', 'hepdata-instance')

static_folder = os.getenv(env_prefix + '_STATIC_FOLDER') or \
    os.path.join(instance_path, 'static')


create_api = create_app_factory(
    'hepdata',
    config_loader=conf_loader,
    extension_entry_points=['invenio_base.api_apps'],
    blueprint_entry_points=['invenio_base.api_blueprints'],
    instance_path=instance_path,
)
```

and in config.py I have 

```python

ACCOUNTS_USE_CELERY = False

```

**Comment by jirikuncar** [comment]
And if you remove https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/ext.py#L73-L78 does it work? IMHO it's problem with configuration loading not with the logic in this module.

**Comment by eamonnmag** [comment]
I need to check. Sorting out db sessions again for now :) Will get back to you shortly!
