### ISSUE TITLE
views: support for optional recaptcha in registration

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-accounts#91]
See:
https://github.com/zenodo/invenio/blob/zenodo-master/invenio/modules/accounts/forms.py#L252
https://flask-wtf.readthedocs.org/en/latest/config.html#recaptcha
https://pythonhosted.org/Flask-Security/customizing.html#forms

Example on Zenodo:
https://zenodo.org/youraccount/register

**Comment by jirikuncar** [comment]
Closed via 8af28c6b
