### ISSUE TITLE
tests: repeated arg-less calls to `create_test_user` throw error

### ISSUE THREAD

**Issue by otron** [inveniosoftware/invenio-accounts#93]
Calling `testutils.py:create_test_user` without any arguments twice cause an error to be thrown as it attempts to create a second user with the default email address.

Fix: generate random email address when none is given instead of using a static default.

**Comment by jirikuncar** [comment]
### Proposal

Make `email` argument required.

**Comment by otron** [comment]
What if, instead of completely random and different between each test run, we use a static seed for the RNG (reset between each test) so that the the nth generated email is always the same?

**Comment by jirikuncar** [comment]
What is the difference if I write `users = [create_test_user('test{0}@example.com') for i in range(10)]`?

**Comment by otron** [comment]
Between your example and `users = [create_test_user() for _ in range(10)]` where the emails are generated from a statically seeded rng? The produced lists will contain different email addresses.

**Comment by tiborsimko** [comment]
Some comments:

- making email address mandatory when creating a user seems good;

- using numerical IDs works just as well as using RNG, so I'd prefer its simplicity;

- it's better to use `example.org` than `example.com` here and elsewhere.

**Comment by otron** [comment]
Generation suggestion:
- `email = "testuser{0}@example.org".format(var)`
   - where `var` is `1` if the number of users in the datastore is `0`, or the largest user id currently in the datastore plus 1.

Why I favor automatic email generation:
- It's a testing utility, meant to make writing tests easier and less of a chore. Making the `email` parameter required increases the amount of effort needed to write tests.
- The email address is only relevant to the test if its value is expected to alter the outcome of the test (e.g. tests for the email validation system or when testing user registration with already registered emails).
