### ISSUE TITLE
session backend needs to be configurable.

### ISSUE THREAD

**Issue by eamonnmag** [inveniosoftware/invenio-accounts#99]
Set CONFIG parameter for session backend. Otherwise it tries to use localhost:6379 as a back end. In production we have nodes dedicated as a redis host so this needs to be a variable.

See
https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/ext.py#L67

We need something like.
```python
r = redis.StrictRedis(host=config['SESSION_REDIS_HOST'], port=config['SESSION_REDIS_PORT'], db=config['SESSION_REDIS_DB'])
```

We already have CACHE_REDIS_HOST as a config param. If we could use this by default, that would be great. The only annoying thing is that the port and db have to be specified, so the host can't be the full connection string.

**Comment by jirikuncar** [comment]
- addresses #65  /cc @lnielsen

**Comment by eamonnmag** [comment]
@jirikuncar and @lnielsen - I'm fixing this now. But how do you prefer the config? Should we split the SESSION_REDIS config in to  SESSION_REDIS_HOST, SESSION_REDIS_PORT, and SESSION_REDIS_DB?

**Comment by jirikuncar** [comment]
`ACCOUNTS_(KW)SESSION_REDIS_URL`?

**Comment by eamonnmag** [comment]
Sure. And we set the defaults in the init_config method to host localhost, port 6379 and db 0

**Comment by lnielsen** [comment]
:+1:
